/*
 *  This file is part of PowellSnakes.
 *
 *  PowellSnakes is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  PowellSnakes is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with PowellSnakes; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

/*
 *  PowellSnakes is being developed by Pedro Carvalho with the scientific advice of:
 *
 *  Dr.		Michael Hobson
 *  Prof.	Anthony Lasenby
 *	Dr.		Graca Rocha
 */

/*
 *  Copyright (C) 2005, 2012, Pedro Carvalho
 *  Author: Pedro Carvalho
 */


#ifndef ZEUS_STRINGS
#define ZEUS_STRINGS

#define	MAKEWCHARARR(t)				MAKEWCHARARR_AUX(t)
#define	MAKECHARARR(t)				MAKECHARARR_AUX(t)

#define	MAKEWCHARARR_AUX(t)			L ## #t
#define	MAKECHARARR_AUX(t)			#t

#define	EXPAND( t )					t

#define ADDSUFFIXNUMBERAUX(VARNAME,VALUE)	VARNAME ## VALUE
#define	ADDSUFFIXNUMBER(VARNAME,VALUE)		ADDSUFFIXNUMBERAUX(VARNAME,VALUE)			


#define	MC_MAKEMAPPROPNAMEAUX(INDEX,SUFFIX)	file ## INDEX ## SUFFIX
	
#define	MC_MAKEMAPPROPNAME(INDEX,SUFFIX)	MC_MAKEMAPPROPNAMEAUX(INDEX,SUFFIX)	

// Global identifiers

#define MCID_GALACTICCUT			galactic_cut
#define MCID_MAPCUTTERID			map_cutter_id
#define	MCID_COMMANDFLAG			command
#define	MCID_PATCHSZ				patchsz
#define MCID_PBORDER				pborder
#define MCID_NLINEPTS				nline_ptch
#define MCID_NSIDE					nside
#define MCID_EPOCH					epoch
#define MCID_MASLENLAGTH			mask_grow_threshold
#define MCID_RMSREJECTLEVEL			rms_reject_level
#define MCID_NOFFILES				n_files
#define MCID_SYNCID					sync_id
#define MCID_MASKFWHM				mask_smooth_fwhm
#define MCID_PERCENTREJECT			badpix_reject_ratio
#define MCID_PTGSCOORDSYS			ptgs_coordsys
#define MCID_MASKREJECTNAME			reject_mask_name
#define MCID_MASKREMOVENAME			remove_mask_name
#define MCID_NONBLINDPTGSFILE		non_blind_ptgs_file
#define MCID_MASKRADIUSRATIO		mask_radius_ratio

#define MC_FILEID					file
#define MC_FILEMAPTYPE				_map_type
#define MC_FILEUNITS				_units
#define MC_FILECOORDSYS				_coordsys
#define MC_FILEUNITCONVFACTOR		_unit_conv_factor
#define MC_FILEANTFWHM				_antfwhm
#define MC_FILEFREQ					_freq
#define MC_FILEFREQID				_freqid
#define MC_FILEMAPFILENAME			_map_file
#define MC_FILEPSCATFILENAME		_pscat_file
#define MC_FILEPROCESSED			_processed
#define MC_THRESSUB					_thr_sub
#define MC_THRESMASK				_thr_mask

#define GLOBALID_DIRIN				dir_data
#define GLOBALID_DIROUTDATA			dir_out_data
#define GLOBALID_DIRBUFERDATA		data_buffer
#define GLOBALID_DIRINMAPS			dir_in_maps
#define GLOBALID_POINTINGS			dir_pointings
#define GLOBALID_DIRINMASKS			dir_masks
#define GLOBALID_DIRINMASKSIN		dir_masks_in

#define HFIDMC_GLOBALID_DIRIN		patches_end		
#define HFIDMC_GLOBALID_DIRINMAPS	obsfreq0000
#define HFIDMC_GLOBALID_POINTINGS	pointings_end

#define GLOBALID_MASKFILENAME		file_mask
#define GLOBALID_DATASETNAME		data_set_name
#define GLOBALID_NFREQS				n_obs_planes
#define GLOBALID_NPRIORPLANES		n_prior_planes
#define GLOBALID_USEBOUNDS			use_bounds
#define GLOBALID_BOUNDTOL			bound_tol
#define GLOBALID_NOTALIGNEDOBJS		not_aligned_objs
#define GLOBALID_TWOSTEPSDETECT		detection_steps
#define GLOBALID_NONBLINDDETECTION	nonblind_detection
#define GLOBALID_CATMERGE_AVGT		output_merge_av_gt
#define GLOBALID_PWSSEARCHPOS		pws_search_pos
#define GLOBALID_USE2DFORMULA		use_2d_formula
#define GLOBALID_NSCALEBINS			n_scale_bins
#define GLOBALID_SSUB_THRESHOLD		ssub_gaussthres
#define GLOBALID_SIGMA_THRESHOLD	sigma_threshold
#define GLOBALID_ASSESS_TYPE		assessment_type
#define GLOBALID_AVREJCTTHRSH		average_reject_threshold
#define GLOBALID_SZDETECTION		sz_detection
#define GLOBALID_JFESTIMATTYPE		jeffreys_estimator
#define GLOBALID_SZVIRIALRATIO		sz_virial_ratio
#define GLOBALID_SRCMAXSCALE		src_max_scale
#define GLOBALID_APODIZEMAPS		apodize_maps
#define GLOBALID_CACHESZ			obj_cache_sz
#define GLOBALID_OUTPUTCOORDS		output_coords
#define GLOBALID_OUTPUTLAT			output_lat
#define GLOBALID_OUTPUTDEGREES		output_degrees
#define GLOBALID_FLUXCALIBCTE		flux_calib_cte
#define GLOBALID_MELTMAXDIST		output_melt_max_dist
#define GLOBALID_MELTMAXDISTSZLIMIT	output_melt_max_dist_sz_limit
#define GLOBALID_CATALOGUESIGMA		output_sigma
#define GLOBALID_GALACTICSIGMA		output_gal_sigma
#define GLOBALID_OUTUNITS			output_units
#define GLOBALID_GALACTICCUT		output_gal_cut
#define GLOBALID_FLUXTHRESHOLD		output_flux_threshold
#define GLOBALID_OUTPURITY			output_purity
#define GLOBALID_FILTERINGSCALES	filtering_scales
#define GLOBALID_OUTPUTRADIUSCAL	output_radius_cal
#define GLOBALID_SZPROFILE			sz_profile
#define GLOBALID_PRIORMAPTYPE		priormap_type
#define GLOBALID_PRIORMAPFREQ		priormap_freq
#define GLOBALID_PRIORMAXL			priormap_maxl
#define GLOBALID_PRIORNPNOISERMS	priormap_noise_rms
#define GLOBALID_PRIORFLUXMIN		priorflux_min
#define GLOBALID_PRIORFLUXMAX		priorflux_max
#define GLOBALID_PRIORFLUXEXP		priorflux_exp
#define GLOBALID_PRIORRADDISTMIN	priorraddist_min
#define GLOBALID_PRIORRADDISTMAX	priorraddist_max
#define GLOBALID_PRIORMASSMIN		priormass_min
#define GLOBALID_PRIORMASSMAX		priormass_max
#define GLOBALID_PRIORMAXZ			priorredshift_max
#define GLOBALID_PRIORTEMPMIN		priortemp_min
#define GLOBALID_PRIORTEMPMAX		priortemp_max
#define GLOBALID_PRIORGASMASSRATIO	priorgasmassratio
#define GLOBALID_PRIORSIGMA8		priorsigma8
#define GLOBALID_USEPRESSSCHT		mass_function
#define GLOBALID_MN_NLIVEPOINTS		mn_nlivepoints
#define GLOBALID_MN_NINDIVSAMPLES	mn_nindivsamples
#define GLOBALID_MN_FRACTOLEV		mn_fractolev
#define GLOBALID_MN_XTRAENLFACT		mn_xtraenlfact
#define GLOBALID_PRIORSRCSCALEMIN	priorsrcscale_min
#define GLOBALID_PRIORSRCSCALEEXP	priorsrcscale_exp
#define GLOBALID_PRIORAVSRCPATCH	prior_nsrcs_area
#define GLOBALID_PRIORSRCSCALEMAX	priorsrcscale_max
#define GLOBALID_OBSPLANEFREQ		obsfreq
#define GLOBALID_SZPROFVARALPHAMIN	szprofpar_alpha_min
#define GLOBALID_SZPROFVARALPHAMAX	szprofpar_alpha_max
#define GLOBALID_SZPROFVARALPHABIN	szprofpar_alpha_bins
#define GLOBALID_SZPROFVARBETAMIN	szprofpar_beta_min
#define GLOBALID_SZPROFVARBETAMAX	szprofpar_beta_max
#define GLOBALID_SZPROFVARBETABIN	szprofpar_beta_bins
#define GLOBALID_SZPROFVARC500MIN	szprofpar_c500_min
#define GLOBALID_SZPROFVARC500MAX	szprofpar_c500_max
#define GLOBALID_SZPROFVARC500BIN	szprofpar_c500_bins
#define	GEOHEADERID_NSIZE			n_size
#define	GEOHEADERID_PATCHSZ			patch_sz
#define	GEOHEADERID_PATCHBORDER		patch_border
#define	GEOHEADERID_TOTPATCHES		total_patches
#define	GEOHEADERID_PIXSZ			pixel_sz
#define	GEOHEADERID_PRAVOBJINPATCH	prior_nsrcs_patch

#define GLOBALID_OBSPLANEFWHM		obsfwhm
#define GLOBALID_FIRSTPATCH			first_patch
#define GLOBALID_LASTPATCH			last_patch
#define GLOBALID_INTCATNAME			intermed_cat_name
#define GLOBALID_FINALCATNAME		final_cat_name		

#define GLOBALID_SZPROFALPHA		sz_profile_alpha
#define GLOBALID_SZPROFBETA			sz_profile_beta
#define GLOBALID_SZPROFGAMMA		sz_profile_gamma
#define GLOBALID_SZPROF_C500		sz_profile_c500
#define GLOBALID_SZPROFCY500CYR500	sz_profile_cy500cyr500
#define GLOBALID_SZPROF2NDMOMENT	sz_profile_2ndMoment1D


#define GLOBALID_OBSPLANEFREQ0000	ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFREQ,0000)
#define GLOBALID_OBSPLANEFREQ0001	ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFREQ,0001)
#define GLOBALID_OBSPLANEFREQ0002	ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFREQ,0002)
#define GLOBALID_OBSPLANEFREQ0003	ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFREQ,0003)
#define GLOBALID_OBSPLANEFREQ0004	ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFREQ,0004)
#define GLOBALID_OBSPLANEFREQ0005	ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFREQ,0005)
#define GLOBALID_OBSPLANEFREQ0006	ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFREQ,0006)
#define GLOBALID_OBSPLANEFREQ0007	ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFREQ,0007)
#define GLOBALID_OBSPLANEFREQ0008	ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFREQ,0008)

#define GLOBALID_FWHM0000		ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFWHM,0000)
#define GLOBALID_FWHM0001		ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFWHM,0001)
#define GLOBALID_FWHM0002		ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFWHM,0002)
#define GLOBALID_FWHM0003		ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFWHM,0003)
#define GLOBALID_FWHM0004		ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFWHM,0004)
#define GLOBALID_FWHM0005		ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFWHM,0005)
#define GLOBALID_FWHM0006		ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFWHM,0006)
#define GLOBALID_FWHM0007		ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFWHM,0007)
#define GLOBALID_FWHM0008		ADDSUFFIXNUMBER(GLOBALID_OBSPLANEFWHM,0008)

#define MC_FILEIDSTR				MAKEWCHARARR(MC_FILEID)
#define MC_FILEMAPTYPESTR			MAKEWCHARARR(MC_FILEMAPTYPE)
#define MC_FILEUNITSSTR				MAKEWCHARARR(MC_FILEUNITS)
#define MC_FILECOORDSYSSTR			MAKEWCHARARR(MC_FILECOORDSYS)
#define MC_FILEUNITCONVFACTORSTR	MAKEWCHARARR(MC_FILEUNITCONVFACTOR)
#define MC_FILEANTFWHMSTR			MAKEWCHARARR(MC_FILEANTFWHM)
#define MC_FILEFREQSTR				MAKEWCHARARR(MC_FILEFREQ)
#define	MC_FILEFREQIDSTR			MAKEWCHARARR(MC_FILEFREQID)
#define MC_FILEMAPFILENAMESTR		MAKEWCHARARR(MC_FILEMAPFILENAME)
#define MC_FILEPSCATFILENAMESTR		MAKEWCHARARR(MC_FILEPSCATFILENAME)
#define MC_FILEPROCESSEDSTR			MAKEWCHARARR(MC_FILEPROCESSED)
#define MC_THRESSUBSTR				MAKEWCHARARR(MC_THRESSUB)
#define MC_THRESMASKSTR				MAKEWCHARARR(MC_THRESMASK)
#define MC_GALACTICCUT				MAKEWCHARARR(MCID_GALACTICCUT)
#define MC_MAPCUTTERID				MAKEWCHARARR(MCID_MAPCUTTERID)
#define MC_COMMANDFLAG				MAKEWCHARARR(MCID_COMMANDFLAG)
#define MC_NSIDE					MAKEWCHARARR(MCID_NSIDE)
#define MC_PATCHSZ					MAKEWCHARARR(MCID_PATCHSZ)
#define MC_PBORDER					MAKEWCHARARR(MCID_PBORDER)
#define MC_NLINEPTS					MAKEWCHARARR(MCID_NLINEPTS)
#define MC_EPOCH					MAKEWCHARARR(MCID_EPOCH)
#define MC_MASLENLAGTH				MAKEWCHARARR(MCID_MASLENLAGTH)
#define MC_RMSREJECTLEVEL			MAKEWCHARARR(MCID_RMSREJECTLEVEL)
#define MC_NOFFILES					MAKEWCHARARR(MCID_NOFFILES)
#define MC_SYNCID					MAKEWCHARARR(MCID_SYNCID)
#define MC_MASKFWHM					MAKEWCHARARR(MCID_MASKFWHM)
#define MC_PERCENTREJECT			MAKEWCHARARR(MCID_PERCENTREJECT)
#define MC_PTGSCOORDSYS				MAKEWCHARARR(MCID_PTGSCOORDSYS)
#define MC_MASKREJECTNAME			MAKEWCHARARR(MCID_MASKREJECTNAME)
#define MC_MASKREMOVENAME			MAKEWCHARARR(MCID_MASKREMOVENAME)
#define MC_NONBLINDPTGSFILE			MAKEWCHARARR(MCID_NONBLINDPTGSFILE)
#define MC_MASKRADIUSRATIO			MAKEWCHARARR(MCID_MASKRADIUSRATIO)

// -------------------------------------------------------------------------------

#define	MC_FILEMAPNAME0000			MC_MAKEMAPPROPNAME(0000,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0000				MC_MAKEMAPPROPNAME(0000,MC_FILEFREQ)
#define	MC_FILEUNITS0000			MC_MAKEMAPPROPNAME(0000,MC_FILEUNITS)
#define	MC_FILECOORDSYS0000			MC_MAKEMAPPROPNAME(0000,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0000			MC_MAKEMAPPROPNAME(0000,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0000	MC_MAKEMAPPROPNAME(0000,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0000		MC_MAKEMAPPROPNAME(0000,MC_FILEPROCESSED)
#define	MC_FILEFREQID0000			MC_MAKEMAPPROPNAME(0000,MC_FILEFREQID)
#define	MC_FILEAFWHM0000			MC_MAKEMAPPROPNAME(0000,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0000			MC_MAKEMAPPROPNAME(0000,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0000			MC_MAKEMAPPROPNAME(0000,MC_THRESSUB)
#define	MC_FILETHMASK0000			MC_MAKEMAPPROPNAME(0000,MC_THRESMASK)

#define	MC_FILEMAPNAME0001			MC_MAKEMAPPROPNAME(0001,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0001				MC_MAKEMAPPROPNAME(0001,MC_FILEFREQ)
#define	MC_FILEUNITS0001			MC_MAKEMAPPROPNAME(0001,MC_FILEUNITS)
#define	MC_FILECOORDSYS0001			MC_MAKEMAPPROPNAME(0001,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0001			MC_MAKEMAPPROPNAME(0001,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0001	MC_MAKEMAPPROPNAME(0001,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0001		MC_MAKEMAPPROPNAME(0001,MC_FILEPROCESSED)
#define	MC_FILEFREQID0001			MC_MAKEMAPPROPNAME(0001,MC_FILEFREQID)
#define	MC_FILEAFWHM0001			MC_MAKEMAPPROPNAME(0001,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0001			MC_MAKEMAPPROPNAME(0001,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0001			MC_MAKEMAPPROPNAME(0001,MC_THRESSUB)
#define	MC_FILETHMASK0001			MC_MAKEMAPPROPNAME(0001,MC_THRESMASK)

#define	MC_FILEMAPNAME0002			MC_MAKEMAPPROPNAME(0002,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0002				MC_MAKEMAPPROPNAME(0002,MC_FILEFREQ)
#define	MC_FILEUNITS0002			MC_MAKEMAPPROPNAME(0002,MC_FILEUNITS)
#define	MC_FILECOORDSYS0002			MC_MAKEMAPPROPNAME(0002,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0002			MC_MAKEMAPPROPNAME(0002,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0002	MC_MAKEMAPPROPNAME(0002,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0002		MC_MAKEMAPPROPNAME(0002,MC_FILEPROCESSED)
#define	MC_FILEFREQID0002			MC_MAKEMAPPROPNAME(0002,MC_FILEFREQID)
#define	MC_FILEAFWHM0002			MC_MAKEMAPPROPNAME(0002,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0002			MC_MAKEMAPPROPNAME(0002,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0002			MC_MAKEMAPPROPNAME(0002,MC_THRESSUB)
#define	MC_FILETHMASK0002			MC_MAKEMAPPROPNAME(0002,MC_THRESMASK)

#define	MC_FILEMAPNAME0003			MC_MAKEMAPPROPNAME(0003,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0003				MC_MAKEMAPPROPNAME(0003,MC_FILEFREQ)
#define	MC_FILEUNITS0003			MC_MAKEMAPPROPNAME(0003,MC_FILEUNITS)
#define	MC_FILECOORDSYS0003			MC_MAKEMAPPROPNAME(0003,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0003			MC_MAKEMAPPROPNAME(0003,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0003	MC_MAKEMAPPROPNAME(0003,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0003		MC_MAKEMAPPROPNAME(0003,MC_FILEPROCESSED)
#define	MC_FILEFREQID0003			MC_MAKEMAPPROPNAME(0003,MC_FILEFREQID)
#define	MC_FILEAFWHM0003			MC_MAKEMAPPROPNAME(0003,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0003			MC_MAKEMAPPROPNAME(0003,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0003			MC_MAKEMAPPROPNAME(0003,MC_THRESSUB)
#define	MC_FILETHMASK0003			MC_MAKEMAPPROPNAME(0003,MC_THRESMASK)

#define	MC_FILEMAPNAME0004			MC_MAKEMAPPROPNAME(0004,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0004				MC_MAKEMAPPROPNAME(0004,MC_FILEFREQ)
#define	MC_FILEUNITS0004			MC_MAKEMAPPROPNAME(0004,MC_FILEUNITS)
#define	MC_FILECOORDSYS0004			MC_MAKEMAPPROPNAME(0004,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0004			MC_MAKEMAPPROPNAME(0004,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0004	MC_MAKEMAPPROPNAME(0004,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0004		MC_MAKEMAPPROPNAME(0004,MC_FILEPROCESSED)
#define	MC_FILEFREQID0004			MC_MAKEMAPPROPNAME(0004,MC_FILEFREQID)
#define	MC_FILEAFWHM0004			MC_MAKEMAPPROPNAME(0004,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0004			MC_MAKEMAPPROPNAME(0004,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0004			MC_MAKEMAPPROPNAME(0004,MC_THRESSUB)
#define	MC_FILETHMASK0004			MC_MAKEMAPPROPNAME(0004,MC_THRESMASK)

#define	MC_FILEMAPNAME0005			MC_MAKEMAPPROPNAME(0005,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0005				MC_MAKEMAPPROPNAME(0005,MC_FILEFREQ)
#define	MC_FILEUNITS0005			MC_MAKEMAPPROPNAME(0005,MC_FILEUNITS)
#define	MC_FILECOORDSYS0005			MC_MAKEMAPPROPNAME(0005,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0005			MC_MAKEMAPPROPNAME(0005,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0005	MC_MAKEMAPPROPNAME(0005,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0005		MC_MAKEMAPPROPNAME(0005,MC_FILEPROCESSED)
#define	MC_FILEFREQID0005			MC_MAKEMAPPROPNAME(0005,MC_FILEFREQID)
#define	MC_FILEAFWHM0005			MC_MAKEMAPPROPNAME(0005,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0005			MC_MAKEMAPPROPNAME(0005,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0005			MC_MAKEMAPPROPNAME(0005,MC_THRESSUB)
#define	MC_FILETHMASK0005			MC_MAKEMAPPROPNAME(0005,MC_THRESMASK)

#define	MC_FILEMAPNAME0006			MC_MAKEMAPPROPNAME(0006,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0006				MC_MAKEMAPPROPNAME(0006,MC_FILEFREQ)
#define	MC_FILEUNITS0006			MC_MAKEMAPPROPNAME(0006,MC_FILEUNITS)
#define	MC_FILECOORDSYS0006			MC_MAKEMAPPROPNAME(0006,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0006			MC_MAKEMAPPROPNAME(0006,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0006	MC_MAKEMAPPROPNAME(0006,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0006		MC_MAKEMAPPROPNAME(0006,MC_FILEPROCESSED)
#define	MC_FILEFREQID0006			MC_MAKEMAPPROPNAME(0006,MC_FILEFREQID)
#define	MC_FILEAFWHM0006			MC_MAKEMAPPROPNAME(0006,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0006			MC_MAKEMAPPROPNAME(0006,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0006			MC_MAKEMAPPROPNAME(0006,MC_THRESSUB)
#define	MC_FILETHMASK0006			MC_MAKEMAPPROPNAME(0006,MC_THRESMASK)

#define	MC_FILEMAPNAME0007			MC_MAKEMAPPROPNAME(0007,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0007				MC_MAKEMAPPROPNAME(0007,MC_FILEFREQ)
#define	MC_FILEUNITS0007			MC_MAKEMAPPROPNAME(0007,MC_FILEUNITS)
#define	MC_FILECOORDSYS0007			MC_MAKEMAPPROPNAME(0007,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0007			MC_MAKEMAPPROPNAME(0007,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0007	MC_MAKEMAPPROPNAME(0007,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0007		MC_MAKEMAPPROPNAME(0007,MC_FILEPROCESSED)
#define	MC_FILEFREQID0007			MC_MAKEMAPPROPNAME(0007,MC_FILEFREQID)
#define	MC_FILEAFWHM0007			MC_MAKEMAPPROPNAME(0007,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0007			MC_MAKEMAPPROPNAME(0007,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0007			MC_MAKEMAPPROPNAME(0007,MC_THRESSUB)
#define	MC_FILETHMASK0007			MC_MAKEMAPPROPNAME(0007,MC_THRESMASK)

#define	MC_FILEMAPNAME0008			MC_MAKEMAPPROPNAME(0008,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0008				MC_MAKEMAPPROPNAME(0008,MC_FILEFREQ)
#define	MC_FILEUNITS0008			MC_MAKEMAPPROPNAME(0008,MC_FILEUNITS)
#define	MC_FILECOORDSYS0008			MC_MAKEMAPPROPNAME(0008,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0008			MC_MAKEMAPPROPNAME(0008,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0008	MC_MAKEMAPPROPNAME(0008,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0008		MC_MAKEMAPPROPNAME(0008,MC_FILEPROCESSED)
#define	MC_FILEFREQID0008			MC_MAKEMAPPROPNAME(0008,MC_FILEFREQID)
#define	MC_FILEAFWHM0008			MC_MAKEMAPPROPNAME(0008,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0008			MC_MAKEMAPPROPNAME(0008,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0008			MC_MAKEMAPPROPNAME(0008,MC_THRESSUB)
#define	MC_FILETHMASK0008			MC_MAKEMAPPROPNAME(0008,MC_THRESMASK)

// ---------------------------------------------------------------------------------

#define	MC_FILEMAPNAME0009			MC_MAKEMAPPROPNAME(0009,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0009				MC_MAKEMAPPROPNAME(0009,MC_FILEFREQ)
#define	MC_FILEUNITS0009			MC_MAKEMAPPROPNAME(0009,MC_FILEUNITS)
#define	MC_FILECOORDSYS0009			MC_MAKEMAPPROPNAME(0009,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0009			MC_MAKEMAPPROPNAME(0009,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0009	MC_MAKEMAPPROPNAME(0009,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0009		MC_MAKEMAPPROPNAME(0009,MC_FILEPROCESSED)
#define	MC_FILEFREQID0009			MC_MAKEMAPPROPNAME(0009,MC_FILEFREQID)
#define	MC_FILEAFWHM0009			MC_MAKEMAPPROPNAME(0009,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0009			MC_MAKEMAPPROPNAME(0009,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0009			MC_MAKEMAPPROPNAME(0009,MC_THRESSUB)
#define	MC_FILETHMASK0009			MC_MAKEMAPPROPNAME(0009,MC_THRESMASK)

#define	MC_FILEMAPNAME0010			MC_MAKEMAPPROPNAME(0010,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0010				MC_MAKEMAPPROPNAME(0010,MC_FILEFREQ)
#define	MC_FILEUNITS0010			MC_MAKEMAPPROPNAME(0010,MC_FILEUNITS)
#define	MC_FILECOORDSYS0010			MC_MAKEMAPPROPNAME(0010,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0010			MC_MAKEMAPPROPNAME(0010,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0010	MC_MAKEMAPPROPNAME(0010,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0010		MC_MAKEMAPPROPNAME(0010,MC_FILEPROCESSED)
#define	MC_FILEFREQID0010			MC_MAKEMAPPROPNAME(0010,MC_FILEFREQID)
#define	MC_FILEAFWHM0010			MC_MAKEMAPPROPNAME(0010,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0010			MC_MAKEMAPPROPNAME(0010,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0010			MC_MAKEMAPPROPNAME(0010,MC_THRESSUB)
#define	MC_FILETHMASK0010			MC_MAKEMAPPROPNAME(0010,MC_THRESMASK)

#define	MC_FILEMAPNAME0011			MC_MAKEMAPPROPNAME(0011,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0011				MC_MAKEMAPPROPNAME(0011,MC_FILEFREQ)
#define	MC_FILEUNITS0011			MC_MAKEMAPPROPNAME(0011,MC_FILEUNITS)
#define	MC_FILECOORDSYS0011			MC_MAKEMAPPROPNAME(0011,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0011			MC_MAKEMAPPROPNAME(0011,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0011	MC_MAKEMAPPROPNAME(0011,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0011		MC_MAKEMAPPROPNAME(0011,MC_FILEPROCESSED)
#define	MC_FILEFREQID0011			MC_MAKEMAPPROPNAME(0011,MC_FILEFREQID)
#define	MC_FILEAFWHM0011			MC_MAKEMAPPROPNAME(0011,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0011			MC_MAKEMAPPROPNAME(0011,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0011			MC_MAKEMAPPROPNAME(0011,MC_THRESSUB)
#define	MC_FILETHMASK0011			MC_MAKEMAPPROPNAME(0011,MC_THRESMASK)

#define	MC_FILEMAPNAME0012			MC_MAKEMAPPROPNAME(0012,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0012				MC_MAKEMAPPROPNAME(0012,MC_FILEFREQ)
#define	MC_FILEUNITS0012			MC_MAKEMAPPROPNAME(0012,MC_FILEUNITS)
#define	MC_FILECOORDSYS0012			MC_MAKEMAPPROPNAME(0012,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0012			MC_MAKEMAPPROPNAME(0012,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0012	MC_MAKEMAPPROPNAME(0012,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0012		MC_MAKEMAPPROPNAME(0012,MC_FILEPROCESSED)
#define	MC_FILEFREQID0012			MC_MAKEMAPPROPNAME(0012,MC_FILEFREQID)
#define	MC_FILEAFWHM0012			MC_MAKEMAPPROPNAME(0012,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0012			MC_MAKEMAPPROPNAME(0012,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0012			MC_MAKEMAPPROPNAME(0012,MC_THRESSUB)
#define	MC_FILETHMASK0012			MC_MAKEMAPPROPNAME(0012,MC_THRESMASK)

#define	MC_FILEMAPNAME0013			MC_MAKEMAPPROPNAME(0013,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0013				MC_MAKEMAPPROPNAME(0013,MC_FILEFREQ)
#define	MC_FILEUNITS0013			MC_MAKEMAPPROPNAME(0013,MC_FILEUNITS)
#define	MC_FILECOORDSYS0013			MC_MAKEMAPPROPNAME(0013,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0013			MC_MAKEMAPPROPNAME(0013,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0013	MC_MAKEMAPPROPNAME(0013,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0013		MC_MAKEMAPPROPNAME(0013,MC_FILEPROCESSED)
#define	MC_FILEFREQID0013			MC_MAKEMAPPROPNAME(0013,MC_FILEFREQID)
#define	MC_FILEAFWHM0013			MC_MAKEMAPPROPNAME(0013,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0013			MC_MAKEMAPPROPNAME(0013,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0013			MC_MAKEMAPPROPNAME(0013,MC_THRESSUB)
#define	MC_FILETHMASK0013			MC_MAKEMAPPROPNAME(0013,MC_THRESMASK)

#define	MC_FILEMAPNAME0014			MC_MAKEMAPPROPNAME(0014,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0014				MC_MAKEMAPPROPNAME(0014,MC_FILEFREQ)
#define	MC_FILEUNITS0014			MC_MAKEMAPPROPNAME(0014,MC_FILEUNITS)
#define	MC_FILECOORDSYS0014			MC_MAKEMAPPROPNAME(0014,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0014			MC_MAKEMAPPROPNAME(0014,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0014	MC_MAKEMAPPROPNAME(0014,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0014		MC_MAKEMAPPROPNAME(0014,MC_FILEPROCESSED)
#define	MC_FILEFREQID0014			MC_MAKEMAPPROPNAME(0014,MC_FILEFREQID)
#define	MC_FILEAFWHM0014			MC_MAKEMAPPROPNAME(0014,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0014			MC_MAKEMAPPROPNAME(0014,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0014			MC_MAKEMAPPROPNAME(0014,MC_THRESSUB)
#define	MC_FILETHMASK0014			MC_MAKEMAPPROPNAME(0014,MC_THRESMASK)

#define	MC_FILEMAPNAME0015			MC_MAKEMAPPROPNAME(0015,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0015				MC_MAKEMAPPROPNAME(0015,MC_FILEFREQ)
#define	MC_FILEUNITS0015			MC_MAKEMAPPROPNAME(0015,MC_FILEUNITS)
#define	MC_FILECOORDSYS0015			MC_MAKEMAPPROPNAME(0015,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0015			MC_MAKEMAPPROPNAME(0015,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0015	MC_MAKEMAPPROPNAME(0015,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0015		MC_MAKEMAPPROPNAME(0015,MC_FILEPROCESSED)
#define	MC_FILEFREQID0015			MC_MAKEMAPPROPNAME(0015,MC_FILEFREQID)
#define	MC_FILEAFWHM0015			MC_MAKEMAPPROPNAME(0015,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0015			MC_MAKEMAPPROPNAME(0015,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0015			MC_MAKEMAPPROPNAME(0015,MC_THRESSUB)
#define	MC_FILETHMASK0015			MC_MAKEMAPPROPNAME(0015,MC_THRESMASK)

#define	MC_FILEMAPNAME0016			MC_MAKEMAPPROPNAME(0016,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0016				MC_MAKEMAPPROPNAME(0016,MC_FILEFREQ)
#define	MC_FILEUNITS0016			MC_MAKEMAPPROPNAME(0016,MC_FILEUNITS)
#define	MC_FILECOORDSYS0016			MC_MAKEMAPPROPNAME(0016,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0016			MC_MAKEMAPPROPNAME(0016,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0016	MC_MAKEMAPPROPNAME(0016,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0016		MC_MAKEMAPPROPNAME(0016,MC_FILEPROCESSED)
#define	MC_FILEFREQID0016			MC_MAKEMAPPROPNAME(0016,MC_FILEFREQID)
#define	MC_FILEAFWHM0016			MC_MAKEMAPPROPNAME(0016,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0016			MC_MAKEMAPPROPNAME(0016,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0016			MC_MAKEMAPPROPNAME(0016,MC_THRESSUB)
#define	MC_FILETHMASK0016			MC_MAKEMAPPROPNAME(0016,MC_THRESMASK)

#define	MC_FILEMAPNAME0017			MC_MAKEMAPPROPNAME(0017,MC_FILEMAPFILENAME)
#define	MC_FILEFREQ0017				MC_MAKEMAPPROPNAME(0017,MC_FILEFREQ)
#define	MC_FILEUNITS0017			MC_MAKEMAPPROPNAME(0017,MC_FILEUNITS)
#define	MC_FILECOORDSYS0017			MC_MAKEMAPPROPNAME(0017,MC_FILECOORDSYS)
#define	MC_FILEMAPTYPE0017			MC_MAKEMAPPROPNAME(0017,MC_FILEMAPTYPE)
#define	MC_FILEUNITCONVFACTOR0017	MC_MAKEMAPPROPNAME(0017,MC_FILEUNITCONVFACTOR)
#define	MC_FILEPROCESSED0017		MC_MAKEMAPPROPNAME(0017,MC_FILEPROCESSED)
#define	MC_FILEFREQID0017			MC_MAKEMAPPROPNAME(0017,MC_FILEFREQID)
#define	MC_FILEAFWHM0017			MC_MAKEMAPPROPNAME(0017,MC_FILEANTFWHM)
#define	MC_FILEPSCAT0017			MC_MAKEMAPPROPNAME(0017,MC_FILEPSCATFILENAME)
#define	MC_FILETHSUB0017			MC_MAKEMAPPROPNAME(0017,MC_THRESSUB)
#define	MC_FILETHMASK0017			MC_MAKEMAPPROPNAME(0017,MC_THRESMASK)

// ---------------------------------------------------------------------------------
#define GLOBAL_DIRIN				MAKEWCHARARR(GLOBALID_DIRIN)
#define GLOBAL_DIROUTDATA			MAKEWCHARARR(GLOBALID_DIROUTDATA)
#define GLOBAL_DIRBUFERDATA			MAKEWCHARARR(GLOBALID_DIRBUFERDATA)
#define GLOBAL_DIRINMAPS			MAKEWCHARARR(GLOBALID_DIRINMAPS)
#define GLOBAL_DIRINMASKS			MAKEWCHARARR(GLOBALID_DIRINMASKS)
#define GLOBAL_DIRINMASKSIN			MAKEWCHARARR(GLOBALID_DIRINMASKSIN)
#define GLOBAL_POINTINGS			MAKEWCHARARR(GLOBALID_POINTINGS)
#define GLOBAL_MASKFILENAME			MAKEWCHARARR(GLOBALID_MASKFILENAME)
#define GLOBAL_DATASETNAME			MAKEWCHARARR(GLOBALID_DATASETNAME)
#define GLOBAL_NFREQS				MAKEWCHARARR(GLOBALID_NFREQS)
#define GLOBAL_NPRIORPLANES			MAKEWCHARARR(GLOBALID_NPRIORPLANES)
#define GLOBAL_USEBOUNDS			MAKEWCHARARR(GLOBALID_USEBOUNDS)
#define GLOBAL_BOUNDTOL				MAKEWCHARARR(GLOBALID_BOUNDTOL)
#define GLOBAL_NOTALIGNEDOBJS		MAKEWCHARARR(GLOBALID_NOTALIGNEDOBJS)
#define GLOBAL_TWOSTEPSDETECT		MAKEWCHARARR(GLOBALID_TWOSTEPSDETECT)
#define GLOBAL_NONBLINDDETECTION	MAKEWCHARARR(GLOBALID_NONBLINDDETECTION)
#define GLOBAL_CATMERGE_AVGT		MAKEWCHARARR(GLOBALID_CATMERGE_AVGT)
#define GLOBAL_PWSSEARCHPOS			MAKEWCHARARR(GLOBALID_PWSSEARCHPOS)
#define GLOBAL_USE2DFORMULA			MAKEWCHARARR(GLOBALID_USE2DFORMULA)
#define GLOBAL_NSCALEBINS			MAKEWCHARARR(GLOBALID_NSCALEBINS)
#define GLOBAL_SSUB_THRESHOLD		MAKEWCHARARR(GLOBALID_SSUB_THRESHOLD)
#define GLOBAL_SIGMA_THRESHOLD		MAKEWCHARARR(GLOBALID_SIGMA_THRESHOLD)
#define GLOBAL_ASSESS_TYPE			MAKEWCHARARR(GLOBALID_ASSESS_TYPE)
#define GLOBAL_AVREJCTTHRSH			MAKEWCHARARR(GLOBALID_AVREJCTTHRSH)
#define GLOBAL_SZDETECTION			MAKEWCHARARR(GLOBALID_SZDETECTION)
#define GLOBAL_JFESTIMATTYPE		MAKEWCHARARR(GLOBALID_JFESTIMATTYPE)
#define GLOBAL_SZVIRIALRATIO		MAKEWCHARARR(GLOBALID_SZVIRIALRATIO)
#define GLOBAL_SRCMAXSCALE			MAKEWCHARARR(GLOBALID_SRCMAXSCALE)
#define GLOBAL_APODIZEMAPS			MAKEWCHARARR(GLOBALID_APODIZEMAPS)
#define GLOBAL_CACHESZ				MAKEWCHARARR(GLOBALID_CACHESZ)
#define GLOBAL_OUTPUTCOORDS			MAKEWCHARARR(GLOBALID_OUTPUTCOORDS)
#define GLOBAL_OUTPUTLAT			MAKEWCHARARR(GLOBALID_OUTPUTLAT)
#define GLOBAL_OUTPUTDEGREES		MAKEWCHARARR(GLOBALID_OUTPUTDEGREES)
#define GLOBAL_FLUXCALIBCTE			MAKEWCHARARR(GLOBALID_FLUXCALIBCTE)
#define GLOBAL_MELTMAXDIST			MAKEWCHARARR(GLOBALID_MELTMAXDIST)
#define GLOBAL_MELTMAXDISTSZLIMIT	MAKEWCHARARR(GLOBALID_MELTMAXDISTSZLIMIT)
#define GLOBAL_CATALOGUESIGMA		MAKEWCHARARR(GLOBALID_CATALOGUESIGMA)
#define GLOBAL_GALACTICSIGMA		MAKEWCHARARR(GLOBALID_GALACTICSIGMA)
#define GLOBAL_OUTUNITS				MAKEWCHARARR(GLOBALID_OUTUNITS)
#define GLOBAL_GALACTICCUT			MAKEWCHARARR(GLOBALID_GALACTICCUT)
#define GLOBAL_FLUXTHRESHOLD		MAKEWCHARARR(GLOBALID_FLUXTHRESHOLD)
#define GLOBAL_OUTPURITY			MAKEWCHARARR(GLOBALID_OUTPURITY)
#define GLOBAL_FILTERINGSCALES		MAKEWCHARARR(GLOBALID_FILTERINGSCALES)
#define GLOBAL_OUTPUTRADIUSCAL		MAKEWCHARARR(GLOBALID_OUTPUTRADIUSCAL)
#define GLOBAL_SZPROFILE			MAKEWCHARARR(GLOBALID_SZPROFILE)
#define GLOBAL_OBSPLANEFREQ			MAKEWCHARARR(GLOBALID_OBSPLANEFREQ)
#define GLOBAL_OBSPLANEFWHM			MAKEWCHARARR(GLOBALID_OBSPLANEFWHM)
#define GLOBAL_PRIORMAPTYPE			MAKEWCHARARR(GLOBALID_PRIORMAPTYPE)
#define GLOBAL_PRIORMAPFREQ			MAKEWCHARARR(GLOBALID_PRIORMAPFREQ)
#define GLOBAL_PRIORMAXL			MAKEWCHARARR(GLOBALID_PRIORMAXL)
#define GLOBAL_PRIORNPNOISERMS		MAKEWCHARARR(GLOBALID_PRIORNPNOISERMS)
#define GLOBAL_PRIORFLUXMIN			MAKEWCHARARR(GLOBALID_PRIORFLUXMIN)
#define GLOBAL_PRIORFLUXMAX			MAKEWCHARARR(GLOBALID_PRIORFLUXMAX)
#define GLOBAL_PRIORFLUXEXP			MAKEWCHARARR(GLOBALID_PRIORFLUXEXP)
#define GLOBAL_PRIORRADDISTMIN		MAKEWCHARARR(GLOBALID_PRIORRADDISTMIN)
#define GLOBAL_PRIORRADDISTMAX		MAKEWCHARARR(GLOBALID_PRIORRADDISTMAX)
#define GLOBAL_PRIORMASSMIN			MAKEWCHARARR(GLOBALID_PRIORMASSMIN)
#define GLOBAL_PRIORMASSMAX			MAKEWCHARARR(GLOBALID_PRIORMASSMAX)
#define GLOBAL_PRIORMAXZ			MAKEWCHARARR(GLOBALID_PRIORMAXZ)
#define GLOBAL_PRIORTEMPMIN			MAKEWCHARARR(GLOBALID_PRIORTEMPMIN)
#define GLOBAL_PRIORTEMPMAX			MAKEWCHARARR(GLOBALID_PRIORTEMPMAX)
#define GLOBAL_PRIORGASMASSRATIO	MAKEWCHARARR(GLOBALID_PRIORGASMASSRATIO)
#define GLOBAL_PRIORSIGMA8			MAKEWCHARARR(GLOBALID_PRIORSIGMA8)
#define GLOBAL_USEPRESSSCHT			MAKEWCHARARR(GLOBALID_USEPRESSSCHT)
#define GLOBAL_MN_NLIVEPOINTS		MAKEWCHARARR(GLOBALID_MN_NLIVEPOINTS)
#define GLOBAL_MN_NINDIVSAMPLES		MAKEWCHARARR(GLOBALID_MN_NINDIVSAMPLES)
#define GLOBAL_MN_FRACTOLEV			MAKEWCHARARR(GLOBALID_MN_FRACTOLEV)
#define GLOBAL_MN_XTRAENLFACT		MAKEWCHARARR(GLOBALID_MN_XTRAENLFACT)
#define GLOBAL_PRIORSRCSCALEMIN		MAKEWCHARARR(GLOBALID_PRIORSRCSCALEMIN)
#define GLOBAL_PRIORSRCSCALEEXP		MAKEWCHARARR(GLOBALID_PRIORSRCSCALEEXP)
#define GLOBAL_PRIORAVSRCPATCH		MAKEWCHARARR(GLOBALID_PRIORAVSRCPATCH)
#define GLOBAL_PRIORSRCSCALEMAX		MAKEWCHARARR(GLOBALID_PRIORSRCSCALEMAX)
#define GLOBAL_FIRSTPATCH			MAKEWCHARARR(GLOBALID_FIRSTPATCH)
#define GLOBAL_LASTPATCH			MAKEWCHARARR(GLOBALID_LASTPATCH)
#define GLOBAL_INTCATNAME			MAKEWCHARARR(GLOBALID_INTCATNAME)
#define GLOBAL_FINALCATNAME			MAKEWCHARARR(GLOBALID_FINALCATNAME)
#define GLOBAL_SZPROFALPHA			MAKEWCHARARR(GLOBALID_SZPROFALPHA)
#define GLOBAL_SZPROFBETA			MAKEWCHARARR(GLOBALID_SZPROFBETA)
#define GLOBAL_SZPROFGAMMA			MAKEWCHARARR(GLOBALID_SZPROFGAMMA)
#define GLOBAL_SZPROF_C500			MAKEWCHARARR(GLOBALID_SZPROF_C500)
#define GLOBAL_SZPROFCY500CYR500	MAKEWCHARARR(GLOBALID_SZPROFCY500CYR500)
#define GLOBAL_SZPROF2NDMOMENT		MAKEWCHARARR(GLOBALID_SZPROF2NDMOMENT)
#define GLOBAL_SZPROFVARALPHAMIN	MAKEWCHARARR(GLOBALID_SZPROFVARALPHAMIN)
#define GLOBAL_SZPROFVARALPHAMAX	MAKEWCHARARR(GLOBALID_SZPROFVARALPHAMAX)
#define GLOBAL_SZPROFVARALPHABIN	MAKEWCHARARR(GLOBALID_SZPROFVARALPHABIN)
#define GLOBAL_SZPROFVARBETAMIN		MAKEWCHARARR(GLOBALID_SZPROFVARBETAMIN)
#define GLOBAL_SZPROFVARBETAMAX		MAKEWCHARARR(GLOBALID_SZPROFVARBETAMAX)
#define GLOBAL_SZPROFVARBETABIN		MAKEWCHARARR(GLOBALID_SZPROFVARBETABIN)
#define GLOBAL_SZPROFVARC500MIN		MAKEWCHARARR(GLOBALID_SZPROFVARC500MIN)
#define GLOBAL_SZPROFVARC500MAX		MAKEWCHARARR(GLOBALID_SZPROFVARC500MAX)
#define GLOBAL_SZPROFVARC500BIN		MAKEWCHARARR(GLOBALID_SZPROFVARC500BIN)

#define	HFIDMC_HEALPIXMAP_SCHEME				"SCHEME"
#define	HFIDMC_HEALPIXMAP_SCHEMEMSG				"RING or NESTED"

#define	HFIDMC_HEALPIXMAP_COORSYS				"COORDSYS"
#define	HFIDMC_HEALPIXMAP_COORSYSMSG			"GALACTIC,ECLIPTIC,EQUATORIAL"

#define	HFIDMC_GEOMHEADERINFO_NROW				"NROWS"
#define	HFIDMC_GEOMHEADERINFO_NCOL				"NCOLUMNS"
#define	HFIDMC_GEOMHEADERINFO_NSIDE				"NSIDE"
#define	HFIDMC_GEOMHEADERINFO_PTCHSZ			"PATCHSZ"
#define	HFIDMC_GEOMHEADERINFO_PTCHBORDER		"PATCHBORDER"
#define	HFIDMC_GEOMHEADERINFO_NPCTMPIX			"NPCHMAINPIX"
#define	HFIDMC_GEOMHEADERINFO_NTOTPTCH			"NTOTPATCHES"
#define	HFIDMC_GEOMHEADERINFO_CLLISTSZ			"CLLISTSZ"
#define	HFIDMC_GEOMHEADERINFO_GALCUT			"GALACTICCUT"

#define	HFIDMC_GEOHDCOMMENT_NSIDE				"Map NSIDE"
#define	HFIDMC_GEOHDCOMMENT_PTCHSZ				"Patch size"
#define	HFIDMC_GEOHDCOMMENT_PTCHBORDER			"Patch border"
#define	HFIDMC_GEOHDCOMMENT_NPCTMPIX			"N patches main pixel"
#define	HFIDMC_GEOHDCOMMENT_NTOTPTCH			"Total No of patches"
#define	HFIDMC_GEOHDCOMMENT_CLLISTSZ			"Sz of collated list"
#define	HFIDMC_GEOHDCOMMENT_GALCUT				"Galactic cut"

#define	HFIDMC_NONBLINDHEADER_DEGREES			"DEGRAD"
#define	HFIDMC_NONBLINDHEADER_COORDSYS			"COORDSYS"
#define	HFIDMC_NONBLINDHEADER_EPOCH				"EPOCH"
#define	HFIDMC_NONBLINDHEADER_CATNCOL			"CATNCOLUMNS"
#define	HFIDMC_NONBLINDHEADER_CATNROW			"CATNROWS"
#define	HFIDMC_NONBLINDHEADER_DETCTTYPE			"DETECTION_TYPE"
#define	HFIDMC_NONBLINDHEADER_ESTIMATOR			"ESTIMATOR"
#define	HFIDMC_NONBLINDHEADER_PRIORTYPE			"PRIORS_TYPE"


#define	HFIDMC_NONBLINDHEADER_SZPROF			"SZPROF"
#define	HFIDMC_NONBLINDHEADER_SZVRATIO			"SZVRATIO"
#define	HFIDMC_NONBLINDHEADER_ALPHA				"SZALPHA"
#define	HFIDMC_NONBLINDHEADER_BETA				"SZBETA"
#define	HFIDMC_NONBLINDHEADER_GAMMA				"SZGAMMA"
#define	HFIDMC_NONBLINDHEADER_C500				"SZC500"
#define	HFIDMC_NONBLINDHEADER_CY500CYR500		"SZCY500CYR500"
#define	HFIDMC_NONBLINDHEADER_FLUXCAL			"SZFLUXCAL"
#define	HFIDMC_NONBLINDHEADER_RADCAL			"SZRADCAL"
#define	HFIDMC_NONBLINDHEADER_COLLSTSZ			"COLLSTSZ"


#define	LFIDPC_FIELDNAMEPREF					"FIELDNO_"
#define	LFIDPC_FIELDNAMEPREFW					L"FIELDNO_"


#define	LFIDPC_FIELDNAME(INDEX)					&(*(LFIDPC_FIELDNAMEPREF INDEX))

#define	HFIDMC_GEOMLINESINFO_PATCHN				"PATCHNUMBER"
#define	HFIDMC_GEOMLINESINFO_BASEPIX			"BASEPIXEL"
#define	HFIDMC_GEOMLINESINFO_SPIN				"SPIN"
#define	HFIDMC_GEOMLINESINFO_CCCOL				"PTGCCCOLAT"
#define	HFIDMC_GEOMLINESINFO_CCLON				"PTGCCCOLON"
#define	HFIDMC_GEOMLINESINFO_LDCOL				"PTGLDCOLAT"
#define	HFIDMC_GEOMLINESINFO_LDLON				"PTGLDCOLON"
#define	HFIDMC_GEOMLINESINFO_RDCOL				"PTGRDCOLAT"
#define	HFIDMC_GEOMLINESINFO_RDLON				"PTGRDCOLON"
#define	HFIDMC_GEOMLINESINFO_LUCOL				"PTGLUCOLAT"
#define	HFIDMC_GEOMLINESINFO_LULON				"PTGLULON"
#define	HFIDMC_GEOMLINESINFO_RUCOL				"PTGRUCOLAT"
#define	HFIDMC_GEOMLINESINFO_RULON				"PTGRULON"
#define	HFIDMC_GEOMLINESINFO_RRINIT				"REJRATIOINIT"
#define	HFIDMC_GEOMLINESINFO_ARRFIN				"REJRATIOFINAL"
#define	HFIDMC_GEOMLINESINFO_ROTDIT				"ROTATIONDIR"
#define	HFIDMC_GEOMLINESINFO_PREDFLUX			"PREDFLUX"
#define	HFIDMC_GEOMLINESINFO_PREDRAD			"PREDRAD"
#define	HFIDMC_GEOMLINESINFO_SNR				"SNR"
#define	HFIDMC_GEOMLINESINFO_SRCID				"SRCID"

#define	INTFILE_HEADERINFO_NCOL					"NCOLUMNS"
#define	INTFILE_HEADERINFO_NROW					"NROWS"

#define	INTFILE_FLDNAME_OBJID					"OBJID"
#define	INTFILE_FLDNAME_PATCHN					"PATCHN"
#define	INTFILE_FLDNAME_BAYSTAT					"BAYSTAT"
#define	INTFILE_FLDNAME_GAUSLEV					"GAUSSLEVEL"
#define	INTFILE_FLDNAME_DETSIGMA				"DETSIGMA"
#define	INTFILE_FLDNAME_AMPLNORM				"AMPLNORM"
#define	INTFILE_FLDNAME_SIGMTHRES				"SIGMTHRES"
#define	INTFILE_FLDNAME_BAYSIGMATH				"BAYSIGMATH"
#define	INTFILE_FLDNAME_FLUX					"FLUX"
#define	INTFILE_FLDNAME_BAYFLUXMAX				"BAYFLUXMAX"
#define	INTFILE_FLDNAME_BAYLNRHOTH				"BAYLNRHOTH"
#define	INTFILE_FLDNAME_BAYLNRHO				"BAYLNRHO"
#define	INTFILE_FLDNAME_BAYLNEVID				"BAYLNEVID"
#define	INTFILE_FLDNAME_BAYLNEVIDERR			"BAYLNEVIDERR"
#define	INTFILE_FLDNAME_BAYLNFORMFACT			"BAYLNFORMFACT"
#define	INTFILE_FLDNAME_BAYLNMODRATIO			"BAYLNMODRATIO"
#define	INTFILE_FLDNAME_POSYCOORD				"POSYCOORD"
#define	INTFILE_FLDNAME_POSXCOORD				"POSXCOORD"
#define	INTFILE_FLDNAME_POSBAYYCMAX				"POSBAYYCMAX"
#define	INTFILE_FLDNAME_POSBAYXCMAX				"POSBAYXCMAX"
#define	INTFILE_FLDNAME_POSBAYYCMEAN			"POSBAYYCMEAN"
#define	INTFILE_FLDNAME_POSBAYXCMEAN			"POSBAYXCMEAN"
#define	INTFILE_FLDNAME_POSGALCOLAT				"POSGALCOLAT"
#define	INTFILE_FLDNAME_POSGALLONG				"POSGALLONG"
#define	INTFILE_FLDNAME_FLUXMJYS				"FLUXMJYS"
#define	INTFILE_FLDNAME_COMPARC2				"COMPTARCMIN2"
#define	INTFILE_FLDNAME_RADIUS					"RADIUS"
#define	INTFILE_FLDNAME_BAYRADMAX				"BAYRADMAX"
#define	INTFILE_FLDNAME_ODDS					"ODDS"
#define	INTFILE_FLDNAME_ISNR2					"ISNR"
#define	INTFILE_FLDNAME_INITODDS				"INITODDS"
#define	INTFILE_FLDNAME_FLUXERR					"FLUXER"
#define	INTFILE_FLDNAME_POSERR					"POSERR"
#define	INTFILE_FLDNAME_RADERR					"RADERR"
#define	INTFILE_FLDNAME_FLUXCONV				"FLUXCONV"
#define	INTFILE_FLDNAME_BAYFLUXMEAN				"BAYFLUXMEAN"
#define	INTFILE_FLDNAME_BAYRADMEAN				"BAYRADMEAN"
#define	INTFILE_FLDNAME_POSECLLAT				"POSECLLAT"
#define	INTFILE_FLDNAME_POSECLLON				"POSECLLON"
#define	INTFILE_FLDNAME_POSEQULAT				"POSEQULAT"
#define	INTFILE_FLDNAME_POSEQULON				"POSEQULON"

#define THETAFILEEXT							L"_th"
#define PHIFILEEXT								L"_ph"
#define PTGSPREFIX								L"ptgs"


// Compiling time messages


// Runtime messages
#define PWSMPIINITEXPTMSG							L"\nAn exception [MPI::exception] has occured -> \n"
#define ZEUSPWSINITEXPTMSG							L"\nAn exception [PwS::exception] has occured during the initialisation process -> \n"
#define STDPWSINITEXPTMSG							L"\nPwS received an undefined exception during the initialisation process. No further help, sorry\n"
#define STANDARTEXCPTMSG							L"\nAn exception [std::exception] has occured-> \n"
#define ZEUSPWSEXCPTMSG								L"\nAn exception [PwS::exception] has occured-> \n"
#define UNDEFINEDEXCPTMSG							L"\nAn undefined exception has occured\n"
#define PRESSANYKEYENDMSG							L"\n\nPress any key to terminate the program\n\n"

#define GLOBAL_TIMEERROR									L"Time error ! "
#define GLOBAL_LOGSEPARATOR									L" => "
#define ERRORLOGFILENAME									"pws_errlog"
#define MSGSLOGFILENAME										"pws_msglog"

#define ERROR_INTRO_STRING									L"An error has occurred with the message, '"
#define ERROR_NUMBER_CODE									L"' and Error number : "
#define ERROR_TYPE_INFO										L"  . The type_info returned : "

#define ERRORMSGZEUS(A)										ERROR_COD_ZEUS##A,ERROR_MSG_ZEUS##A

#define ERROR_COD_ZEUSBASE_OFFSET							10

#define ERROR_COD_ZEUSUNDEFINED								ERROR_COD_ZEUSBASE_OFFSET
#define ERROR_MSG_ZEUSUNDEFINED								L"Undefined error"

#define ERROR_COD_ZEUSBADMEMREF								ERROR_COD_ZEUSBASE_OFFSET + 1
#define ERROR_MSG_ZEUSBADMEMREF								L"Bad memory reference."

#define ERROR_COD_ZEUSBADHANDLE								ERROR_COD_ZEUSBASE_OFFSET + 2
#define ERROR_MSG_ZEUSBADHANDLE								L"Invalid handle"

#define ERROR_COD_ZEUSNOTDYNAMC								ERROR_COD_ZEUSBASE_OFFSET + 3
#define ERROR_MSG_ZEUSNOTDYNAMC								L"This class is not a Zeus dynamic class"

#define ERROR_COD_ZEUSUNKNONOBJ								ERROR_COD_ZEUSBASE_OFFSET + 4
#define ERROR_MSG_ZEUSUNKNONOBJ								L"Unknown type. You need to register the type"

#define ERROR_COD_ZEUSCANTINITD								ERROR_COD_ZEUSBASE_OFFSET + 5
#define ERROR_MSG_ZEUSCANTINITD								L"Error initializing a device."

#define ERROR_COD_ZEUSSGNOTINIT								ERROR_COD_ZEUSBASE_OFFSET + 6
#define ERROR_MSG_ZEUSSGNOTINIT								L"Singleton not initialized."

#define ERROR_COD_ZEUSERROPENFL								ERROR_COD_ZEUSBASE_OFFSET + 7
#define ERROR_MSG_ZEUSERROPENFL								L"Error opening file."

#define ERROR_COD_ZEUSGENERRFIL								ERROR_COD_ZEUSBASE_OFFSET + 8
#define ERROR_MSG_ZEUSGENERRFIL								L"General error reading file."

#define ERROR_COD_ZEUSERRPARSLN								ERROR_COD_ZEUSBASE_OFFSET + 9
#define ERROR_MSG_ZEUSERRPARSLN								L"Error parsing line."

#define ERROR_COD_ZEUSVARIANTTY								ERROR_COD_ZEUSBASE_OFFSET + 10
#define ERROR_MSG_ZEUSVARIANTTY								L"Variant error. Trying to access a variant of the wrong type"

#define ERROR_COD_ZEUSMETHONDEF								ERROR_COD_ZEUSBASE_OFFSET + 11
#define ERROR_MSG_ZEUSMETHONDEF								L"Method not yet defined."

#define ERROR_COD_ZEUSFDIVERGES								ERROR_COD_ZEUSBASE_OFFSET + 12
#define ERROR_MSG_ZEUSFDIVERGES								L"Numerical error. Convergence has failed. Method -> "

#define ERROR_COD_ZEUSOUTBOUNDS								ERROR_COD_ZEUSBASE_OFFSET + 13
#define ERROR_MSG_ZEUSOUTBOUNDS								L"Numerical error. Value out of bounds"

#define ERROR_COD_ZEUSNOCLONEOP								ERROR_COD_ZEUSBASE_OFFSET + 14
#define ERROR_MSG_ZEUSNOCLONEOP								L"This object doesn't support the cloning operation."

#define ERROR_COD_ZEUSGLBPARAMRD							ERROR_COD_ZEUSBASE_OFFSET + 15
#define ERROR_MSG_ZEUSGLBPARAMRD							L"Error reading global parameters. Can't find the parameter -> "

#define ERROR_COD_ZEUSGLBPARAMFL							ERROR_COD_ZEUSBASE_OFFSET + 16
#define ERROR_MSG_ZEUSGLBPARAMFL							L"Error reading from the global parameters file. -> "

#define ERROR_COD_ZEUSWRKSPALLOC							ERROR_COD_ZEUSBASE_OFFSET + 17
#define ERROR_MSG_ZEUSWRKSPALLOC							L"Large array not initialized."

#define ERROR_COD_ZEUSINITREADER							ERROR_COD_ZEUSBASE_OFFSET + 18
#define ERROR_MSG_ZEUSINITREADER							L"Error initializing the reader."

#define ERROR_COD_ZEUSREADERNOTINIT							ERROR_COD_ZEUSBASE_OFFSET + 19
#define ERROR_MSG_ZEUSREADERNOTINIT							L"Reader not yet initialized."

#define ERROR_COD_ZEUSINITWRITER							ERROR_COD_ZEUSBASE_OFFSET + 20
#define ERROR_MSG_ZEUSINITWRITER							L"Error initializing the writer."

#define ERROR_COD_ZEUSWRITERNOTINIT							ERROR_COD_ZEUSBASE_OFFSET + 21
#define ERROR_MSG_ZEUSWRITERNOTINIT							L"Writer not yet initialized."

#define ERROR_COD_MYINOUT_FILEWRITE							ERROR_COD_ZEUSBASE_OFFSET + 22
#define ERROR_MSG_MYINOUT_FILEWRITE							L"Error writing file."

#define ERROR_COD_DTSURFWRONGSZ								ERROR_COD_ZEUSBASE_OFFSET + 23
#define ERROR_MSG_DTSURFWRONGSZ								L"X size or Y size is odd."

#define ERROR_COD_DTSURFDIFOBJS								ERROR_COD_ZEUSBASE_OFFSET + 24
#define ERROR_MSG_DTSURFDIFOBJS								L"Cannot multiply different surfaces."

#define ERROR_COD_DTSURFDIFOBJSADD							ERROR_COD_ZEUSBASE_OFFSET + 25
#define ERROR_MSG_DTSURFDIFOBJSADD							L"Cannot add different surfaces."

#define ERROR_COD_MYINOUT_NOHEADER							ERROR_COD_ZEUSBASE_OFFSET + 26
#define ERROR_MSG_MYINOUT_NOHEADER							L"Cannot find the header"

#define ERROR_COD_MYINOUT_FILEPARSE							ERROR_COD_ZEUSBASE_OFFSET + 26
#define ERROR_MSG_MYINOUT_FILEPARSE							L"Error parsing file."

#define ERROR_COD_BINNING									ERROR_COD_ZEUSBASE_OFFSET + 27
#define ERROR_MSG_BINNING									L"Binning array out of bounds or not initialized."

#define ERROR_COD_SURFWRONGSZ								ERROR_COD_ZEUSBASE_OFFSET + 28
#define ERROR_MSG_SURFWRONGSZ								L"Surfaces of wrong sizes."

#define ERROR_COD_VECTOROUTOFBOUNDS							ERROR_COD_ZEUSBASE_OFFSET + 29
#define ERROR_MSG_VECTOROUTOFBOUNDS							L"Reading vector out of bounds"

#define ERROR_COD_MYINOUT_FILEREAD							ERROR_COD_ZEUSBASE_OFFSET + 30
#define ERROR_MSG_MYINOUT_FILEREAD							L"Error reading file."

#define ERROR_COD_TYPEMISMATCH								ERROR_COD_ZEUSBASE_OFFSET + 31
#define ERROR_MSG_TYPEMISMATCH								L"Type mismatch in keyword."

#define ERROR_COD_ZEUSNUMWRONGARGS							ERROR_COD_ZEUSBASE_OFFSET + 32
#define ERROR_MSG_ZEUSNUMWRONGARGS							L"Numerical error. Wrong number of arguments"

#define ERROR_COD_HFIDMC_OFFSET								10000

#define ERROR_COD_HFIDMCERROPENFL							ERROR_COD_HFIDMC_OFFSET + 0
#define ERROR_MSG_HFIDMCERROPENFL							L"Error opening group. "

#define ERROR_COD_HFIDMCERRCREATFL							ERROR_COD_HFIDMC_OFFSET + 1
#define ERROR_MSG_HFIDMCERRCREATFL							L"Error creating group. "

#define ERROR_COD_HFIDMCERROPENIMGFL						ERROR_COD_HFIDMC_OFFSET + 3
#define ERROR_MSG_HFIDMCERROPENIMGFL						L"Error opening image file. "

#define ERROR_COD_HFIDMCERRIMGWRONGSZ						ERROR_COD_HFIDMC_OFFSET + 4
#define ERROR_MSG_HFIDMCERRIMGWRONGSZ						L"Error, patch/catalogue/vect is of wrong size. "

#define ERROR_COD_HFIDMCERROPENHEALPX						ERROR_COD_HFIDMC_OFFSET + 5
#define ERROR_MSG_HFIDMCERROPENHEALPX						L"Error opening Healpix/group map. "

#define ERROR_COD_HFIDMCERRDELETEFL							ERROR_COD_HFIDMC_OFFSET + 6
#define ERROR_MSG_HFIDMCERRDELETEFL							L"Error deleting a group. "

#define ERROR_MSG_HFIDMCREADVECTFORMAT						"Read VECT %s failed\n%s\n"
#define ERROR_MSG_HFIDMCDELETEVECTFORMAT					"Delete VECT %s failed\n%s\n"
#define ERROR_MSG_HFIDMCCREATEVECTFORMAT					"Create VECT %s failed\n%s\n"
#define ERROR_MSG_HFIDMCWRITEVECTFORMAT						"Write VECT %s failed\n%s\n"
#define ERROR_MSG_HFIDMCREADKEYWORDFORMAT					"Read Keyword %s failed\n%s\n"
#define ERROR_MSG_HFIDMCWRITEKEYWORDFORMAT					"Write Keyword %s failed\n%s\n"


#define ERROR_MSG_HFIDMCREADIMGFORMAT						"Read IMG/TABLE %s failed\n%s\n"
#define ERROR_MSG_HFIDMCCREATEIMGFORMAT						"Create IMG/TABLE %s failed\n%s\n"

#define ERROR_MSG_HFIDMCIMGPROPSFORMAT						"Read MAP %s properties failed\n%s\n"
#define ERROR_MSG_HFIDMCIMGMAPREADFORMAT					"Read MAP %s failed\n%s\n"

#define ERROR_MSG_HFIDMCIMGMAPWRITEFORMAT					"Write MAP %s failed\n%s\n"
#define ERROR_MSG_HFIDMCIMGMAPCREATEFORMAT					"Create MAP %s failed\n%s\n"


#define ERROR_MSG_HFIDMCDELETEIMGFORMAT						"Delete IMG/TABLE %s failed\n%s\n"
#define ERROR_MSG_HFIDMCWRITEIMGFORMAT						"Write IMG/TABLE %s failed\n%s\n"
#endif //ZEUS_STRINGS
